# Generated by Django 3.1.4 on 2021-01-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, editable=False)),
                ('is_to_be_deleted', models.BooleanField(default=False, editable=False)),
                ('deletion_date', models.DateField(auto_now_add=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=128)),
                ('information', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
