# Generated by Django 3.1.4 on 2021-01-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-id',)},
        ),
    ]
