# Generated by Django 3.1.4 on 2020-12-21 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('middle_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('is_in_personal_life', models.BooleanField(default=False)),
                ('is_in_work_life', models.BooleanField(default=False)),
                ('relationship', models.CharField(choices=[('frie', 'Friend'), ('part', 'Partner'), ('chil', 'Child'), ('pare', 'Parent'), ('acqu', 'Acquaintance'), ('ment', 'Mentor')], default='frie', max_length=4)),
                ('group', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', related_query_name='people', to='group.group')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish', models.DateTimeField(default=django.utils.timezone.now)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', related_query_name='date', to='people.people')),
            ],
        ),
    ]
